FROM python:3.12-slim

WORKDIR /app

COPY temperature_sensor_simulator/requirements.txt .
COPY humidity_sensor_simulator/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r pytest
