# temp_simulator Dockerfile

FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY temp_simulator.py .

CMD ["python", "temp_simulator.py"]
