# Humididty simulator Dockerfile

FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY humidity_simulator.py .

CMD ["python", "humidity_simulator.py"]
